application:
  name: dev环境 @artifactId@
  version: dev环境 @version@
developer:
  name: dev环境 xiyouquedongxing
  website: dev环境 http://xiyouquedongxing.world
  qq: dev环境 1332332333
  phone-number: dev环境 17688882333